### ISSUE TITLE
Not getting any images

### ISSUE THREAD

**Issue by erikhallgren** [reneepadgham/diverseui-sketch-plugin#4]
Hi, just found out about this awesome plugin! 
But to my dismay no images are displayed, I get no error message so not sure what's going on. 

Using Sketch 47

**Comment by yefim** [comment]
Uh oh :( Thanks for writing in. We'll look into it this weekend!

**Comment by yefim** [comment]
@erikhallgren what Sketch version are you using?

**Comment by erikhallgren** [comment]
@yefim  47.1

**Comment by HPieters** [comment]
+1 Same issue, I get an empty rectangle rather than an image. (47.1)

**Comment by yefim** [comment]
thanks for the reports! I haven't had much time to deal with this lately. I'll try to get to it this weekend :)

**Comment by yefim** [comment]
@erikhallgren @HPieters I just got the fix in. Can you please check to see if it works now? Thank you!

**Comment by erikhallgren** [comment]
No, thank YOU! :)
Works perfectly here now 👍

**Comment by HPieters** [comment]
Hah very late to the party, anyways works like a charm!
